// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-m-y37x3K5VhM7F5MuWl2Cy5ouJQFYfI',
    appId: '1:708203689067:web:b94a943c6e80551efa2d2e',
    messagingSenderId: '708203689067',
    projectId: 'finalproject-f5395',
    authDomain: 'finalproject-f5395.firebaseapp.com',
    storageBucket: 'finalproject-f5395.firebasestorage.app',
    measurementId: 'G-1JVW2B13WK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPkWuhUAUdwbRtmFIF7CMBoC2KrKhSHQ0',
    appId: '1:708203689067:android:778f56ec4b70f232fa2d2e',
    messagingSenderId: '708203689067',
    projectId: 'finalproject-f5395',
    storageBucket: 'finalproject-f5395.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRQO7qw5T6vdsQm5WeTt54BqcSQCORJxk',
    appId: '1:708203689067:ios:4e4599670c3f9422fa2d2e',
    messagingSenderId: '708203689067',
    projectId: 'finalproject-f5395',
    storageBucket: 'finalproject-f5395.firebasestorage.app',
    iosBundleId: 'com.example.derot',
  );
}
